### ISSUE TITLE
debian repo

### ISSUE THREAD

**Issue by moobyfr** [alanfranz/atom-text-editor-repository#1]
It seems that debian repository is broken

**Comment by alanfranz** [comment]
Thanks for your report.

I'm unable to test all versions all the time; would you be so kind to
explain what the issue is, how it happens, and for which debian version?
Il 12/set/2015 08:32 PM, "Blindauer Emmanuel" notifications@github.com ha
scritto:

**Comment by moobyfr** [comment]
Sorry wrong report, I had a pinning issue, and looking into the pool directory, I was thinking the issue was related to these tmp files: http://www.a9f.eu/apt/atom/debian/pool/main/a/atom/
