### ISSUE TITLE
Really interested on beta releases

### ISSUE THREAD

**Issue by mautematico** [alanfranz/atom-text-editor-repository#10]
Hello, there. I am really interested on beta releases.
Is there any way I can help you?

> I'm not hosting beta releases and I don't plan to, right now (open a ticket if you're really interested); I plan to host stable releases only.

**Comment by alanfranz** [comment]
I have pushed the retrieveal script, that I had forgot to made public.

If you provide a new script with what should go on the beta channel (beta only? beta+stable if stable > beta? you should decide and argument that choice) I'll setup the automatic publishing (although that should be fairly easy to do on any public CI hosting). 

The script should download the deb and the rpm to the current directory, and should add any downloaded version to the state file, so it doesn't get redownloaded in the future.

**Comment by alanfranz** [comment]
Closing the project, since upstream maintainers now provide a repository.
