### ISSUE TITLE
RPM package is outdated. 

### ISSUE THREAD

**Issue by jerome-benoit** [alanfranz/atom-text-editor-repository#12]
Thank for the repository work. 

The current RPM package made available is a little bit outdated : 
```
[fraggle@nemesis.2:~]$ rpm -q atom
atom-1.30.0-0.1.x86_64
```
Could you please sync the rpm version made available to the latest, like the deb one ? 

Cheers.

**Comment by mfonville** [comment]
Also could you please release atom 1.32 for Debian/Ubuntu? It fixes the glibc issues that Ubuntu Cosmic users experience.

**Comment by jerome-benoit** [comment]
On 25/10/2018 14:58, Maarten Fonville wrote:
>
> Also could you please release atom 1.32 for Debian/Ubuntu? It fixes 
> the glibc issues that Ubuntu Cosmic users experience.
>

In fact, there is now official repositories : 
https://flight-manual.atom.io/getting-started/sections/installing-atom/#platform-linux

-- 
Jérôme Benoit aka fraggle
Piment Noir -https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by mfonville** [comment]
Thanks!
