### ISSUE TITLE
How to "add the proper line in /etc/apt/sources.list"?

### ISSUE THREAD

**Issue by mark-hahn** [alanfranz/atom-text-editor-repository#2]
I apologize in advance for being ignorant and/or lazy, but exactly what are the proper lines  to add to /etc/apt/sources.list?

If this would be different for every release then you shouldn't take the trouble.  But could you point to where to figure this out?

**Comment by alanfranz** [comment]
Hello mark-hahn,
the proper lines are those that you see just below, different for each distro and version. I must assume a minimal knowledge of apt-get, the way it works is always the same.

If you take a look at your /etc/apt/sources.list and see what it contains, you'll immediately recognize the pattern.

**Comment by mark-hahn** [comment]
Duh.  I didn't realize the following sections _were_ the `sources.list` lines.  Sorry to bother you.
