### ISSUE TITLE
Wily support

### ISSUE THREAD

**Issue by mfonville** [alanfranz/atom-text-editor-repository#3]
Hey, would you be able to also provide wily support so that we could use the APT line:
deb http://www.a9f.eu/apt/atom/ubuntu wily main
?
thank you!

**Comment by alanfranz** [comment]
Done, added support for wily, xenial in Ubuntu, and Debian Sid as well. 42de0637d32c840df115a9feeb25d774ce20dc92

**Comment by mfonville** [comment]
Thanks!

**Comment by mfonville** [comment]
Ubuntu yakkety will be btw released next week, and everything is already in freeze.
Will you add it to the supported dists?

**Comment by alanfranz** [comment]
Yup. I will do it soon; will appear as downloadable for the next Atom release, by the way.
