### ISSUE TITLE
Offer Debian repositry for testing

### ISSUE THREAD

**Issue by PanderMusubi** [alanfranz/atom-text-editor-repository#6]
Please, offer a Debian repository for testing such as

```
deb http://www.a9f.eu/apt/atom/debian testing main
```

**Comment by alanfranz** [comment]
Hello,
this is just sugar. The package doesn't get rebuilt. Use squeeze/jessie, the deb is the same.

**Comment by alanfranz** [comment]
I'm considering "collapsing" all the Ubuntus/Debians/Fedoras/Centos as well.

**Comment by PanderMusubi** [comment]
Thanks for the explaination. When collapsing, you can call it stable or latest.

**Comment by alanfranz** [comment]
Yes, that was the idea!
