### ISSUE TITLE
Fedora 24

### ISSUE THREAD

**Issue by amayer5125** [alanfranz/atom-text-editor-repository#8]
Can you please enable Fedora 24?

**Comment by alanfranz** [comment]
hello,
fc24 was enabled. next release will be uploaded properly.

you can use the 23 url until then; the package is exactly identical.

**Comment by amayer5125** [comment]
@alanfranz I used fc23 for the time being. Just figured since your instructions use `$releasever` fc24 should be enabled.
Thanks :)
